import type { editor } from "monaco-editor";

export const TRON_DARK: editor.IStandaloneThemeData = {
  base: "vs-dark",
  inherit: false,
  rules: [
    { token: "", foreground: "C5D4E3" },
    { token: "comment", foreground: "4A5868", fontStyle: "italic" },
    { token: "keyword", foreground: "6FC3DF", fontStyle: "bold" },
    { token: "keyword.control", foreground: "9BDDF5" },
    { token: "string", foreground: "FFA500" },
    { token: "string.escape", foreground: "FFB833" },
    { token: "number", foreground: "FF8533" },
    { token: "regexp", foreground: "FFB833" },
    { token: "type", foreground: "9BDDF5" },
    { token: "type.identifier", foreground: "9BDDF5" },
    { token: "class", foreground: "9BDDF5", fontStyle: "bold" },
    { token: "interface", foreground: "6FC3DF" },
    { token: "function", foreground: "C5D4E3", fontStyle: "bold" },
    { token: "variable", foreground: "C5D4E3" },
    { token: "variable.parameter", foreground: "8FA3BD" },
    { token: "constant", foreground: "FF8533" },
    { token: "tag", foreground: "6FC3DF" },
    { token: "attribute.name", foreground: "9BDDF5" },
    { token: "attribute.value", foreground: "FFA500" },
    { token: "delimiter", foreground: "8FA3BD" },
    { token: "delimiter.bracket", foreground: "6FC3DF" },
    { token: "operator", foreground: "9BDDF5" },
    { token: "namespace", foreground: "9BDDF5" },
  ],
  colors: {
    "editor.background": "#05080F",
    "editor.foreground": "#C5D4E3",
    "editor.lineHighlightBackground": "#0A0E1A",
    "editor.selectionBackground": "#6FC3DF33",
    "editor.inactiveSelectionBackground": "#6FC3DF1A",
    "editorCursor.foreground": "#9BDDF5",
    "editorWhitespace.foreground": "#1A2632",
    "editorLineNumber.foreground": "#4A5868",
    "editorLineNumber.activeForeground": "#9BDDF5",
    "editorIndentGuide.background": "#1A2632",
    "editorIndentGuide.activeBackground": "#3A8FB5",
    "editorBracketMatch.background": "#6FC3DF22",
    "editorBracketMatch.border": "#6FC3DF",
    "editorWidget.background": "#0F1622",
    "editorWidget.border": "#6FC3DF33",
    "editorSuggestWidget.background": "#0F1622",
    "editorSuggestWidget.border": "#6FC3DF33",
    "editorSuggestWidget.selectedBackground": "#6FC3DF1A",
    "scrollbar.shadow": "#00000000",
    "scrollbarSlider.background": "#6FC3DF14",
    "scrollbarSlider.hoverBackground": "#6FC3DF22",
    "scrollbarSlider.activeBackground": "#6FC3DF44",
    "minimap.background": "#05080F",
  },
};

export const TRON_DARK_NAME = "tron-dark";
