import type { editor } from "monaco-editor";

// Daisu Nocturne — calm, warm, low-contrast theme tuned for long sessions.
// Filename kept as monaco-tron-theme.ts to avoid churn; identifier renamed
// via re-export below.
export const DAISU_NOCTURNE: editor.IStandaloneThemeData = {
  base: "vs-dark",
  inherit: false,
  rules: [
    { token: "", foreground: "E8E4DA" },
    { token: "comment", foreground: "5A5A66", fontStyle: "italic" },
    { token: "keyword", foreground: "C8A46A", fontStyle: "bold" },
    { token: "keyword.control", foreground: "DDB87A" },
    { token: "string", foreground: "A8C09A" },
    { token: "string.escape", foreground: "B8D0A8" },
    { token: "number", foreground: "D4A574" },
    { token: "regexp", foreground: "B8D0A8" },
    { token: "type", foreground: "B8A8D4", fontStyle: "italic" },
    { token: "type.identifier", foreground: "B8A8D4", fontStyle: "italic" },
    { token: "class", foreground: "B8A8D4", fontStyle: "bold" },
    { token: "interface", foreground: "B8A8D4" },
    { token: "function", foreground: "E8C497" },
    { token: "variable", foreground: "E8E4DA" },
    { token: "variable.parameter", foreground: "A8A296" },
    { token: "constant", foreground: "D4A574" },
    { token: "tag", foreground: "C8A46A" },
    { token: "attribute.name", foreground: "DDB87A" },
    { token: "attribute.value", foreground: "A8C09A" },
    { token: "delimiter", foreground: "8A8478" },
    { token: "delimiter.bracket", foreground: "A8A296" },
    { token: "operator", foreground: "8FA0B8" },
    { token: "namespace", foreground: "B8A8D4" },
  ],
  colors: {
    "editor.background": "#0E0E13",
    "editor.foreground": "#E8E4DA",
    "editor.lineHighlightBackground": "#14141B",
    "editor.lineHighlightBorder": "#00000000",
    "editor.selectionBackground": "#D4A57426",
    "editor.inactiveSelectionBackground": "#D4A57414",
    "editor.wordHighlightBackground": "#D4A57418",
    "editor.findMatchBackground": "#D4A57440",
    "editor.findMatchHighlightBackground": "#D4A57422",
    "editorCursor.foreground": "#D4A574",
    "editorWhitespace.foreground": "#1F1F2A",
    "editorLineNumber.foreground": "#3F3B33",
    "editorLineNumber.activeForeground": "#A8A296",
    "editorIndentGuide.background": "#1A1A23",
    "editorIndentGuide.activeBackground": "#3F3B33",
    "editorBracketMatch.background": "#D4A57418",
    "editorBracketMatch.border": "#D4A57466",
    "editorWidget.background": "#1C1C25",
    "editorWidget.border": "#E8E4DA10",
    "editorSuggestWidget.background": "#1C1C25",
    "editorSuggestWidget.border": "#E8E4DA10",
    "editorSuggestWidget.selectedBackground": "#D4A57414",
    "editorSuggestWidget.highlightForeground": "#E8C497",
    "editorHoverWidget.background": "#1C1C25",
    "editorHoverWidget.border": "#E8E4DA10",
    "editorGutter.background": "#0E0E13",
    "editorOverviewRuler.border": "#00000000",
    "scrollbar.shadow": "#00000000",
    "scrollbarSlider.background": "#E8E4DA0A",
    "scrollbarSlider.hoverBackground": "#E8E4DA14",
    "scrollbarSlider.activeBackground": "#D4A57433",
    "minimap.background": "#0E0E13",
  },
};

// Back-compat alias (consumed by Editor.tsx).
export const TRON_DARK = DAISU_NOCTURNE;
export const TRON_DARK_NAME = "daisu-nocturne";
